Accordion component added.
DanCorder/govuk-design-system-dotnet pull request #3
Opened 2020-02-12 10:48 UTC by asprouc

2020-02-12 12:05 UTC, DanCorder requested changes

2020-02-12 12:05 UTC, DanCorder commented on GovUkDesignSystemComponents/Accordion.cshtml
> +         @($"headingLevel = {Model.HeadingLevel}")
Why include headingLevel here?

2020-02-12 12:05 UTC, DanCorder commented on GovUkDesignSystemComponents/Accordion.cshtml
> +            var headingLevel = section.HeadingLevel;
I don't think the GovUK design allows different heading levels for different sections of the accordion, so we should probably just use Model.HeadingLevel here and remove section.HeadingLevel

2020-02-12 12:05 UTC, DanCorder commented on GovUkDesignSystemComponents/Accordion.cshtml
> +    <div class="govuk-accordion @(Model.Classes)" data-module="govuk-accordion" @(!string.IsNullOrEmpty(Model.Id) ? $"Id = {Model.Id}" : $@"Id = {"accordion-default"}")
I'd be happy to assume the Model.Id is not null or empty, the rest of this library makes that assumption, so if we're going to make it safer we should do so for all the components at once.

2020-02-12 12:05 UTC, DanCorder commented on GovUkDesignSystemComponents/Accordion.cshtml
> +                            <span class="govuk-accordion__section-button" id="accordion-with-summary-sections-heading-1">
Looking at the GovUK design it looks like the id here is meant to be $"{Model.Id}-heading-{SectionIndex}"

2020-02-12 12:05 UTC, DanCorder commented on GovUkDesignSystemComponents/Accordion.cshtml
> +                        <div class="govuk-accordion__section-summary govuk-body" id="accordion-with-summary-sections-summary-1">
I think the id here should be something like $"{Model.Id}-summary-{SectionIndex}"

2020-02-12 12:05 UTC, DanCorder commented on GovUkDesignSystemComponents/Accordion.cshtml
> +                    <div id="accordion-default-content-1" class="govuk-accordion__section-content" aria-labelledby="accordion-default-heading-1">
I think the id here should be something like $"{Model.Id}-content-{SectionIndex}"
Also it looks like the aria-labelledby value should be the id of the span on line 16

2020-02-12 12:05 UTC, DanCorder commented on GovUkDesignSystemComponents/AccordionViewModel.cs
> +        public int HeadingLevel { get; set; }
I believe that you and Waqar discussed the idea of using an enum to limit HeadingLevel to the value 1-6. Could you put that on to this branch?

2020-02-12 12:05 UTC, DanCorder commented on GovUkDesignSystemComponents/AccordionViewModel.cs
> +        public int HeadingLevel { get; set; } = 2;
As mentioned above, I think we can get rid of this property

2020-02-12 12:05 UTC, DanCorder commented on GovUkDesignSystemComponents/Accordion.cshtml
> +                        <p class='govuk-body'>
Looking at the GovUK design it seems that the &lt;p&gt; tags are part of the content passed to the accordion rather than part of the accordion so we should remove them from here.

2020-02-14 14:02 UTC, asprouc commented on GovUkDesignSystemComponents/Accordion.cshtml
> +         @($"headingLevel = {Model.HeadingLevel}")
I have corrected this. However heading level does not seem to work.

2020-02-14 14:04 UTC, asprouc commented on GovUkDesignSystemComponents/Accordion.cshtml
> +            var headingLevel = section.HeadingLevel;
Done.

2020-02-14 14:05 UTC, asprouc commented on GovUkDesignSystemComponents/Accordion.cshtml
> +    <div class="govuk-accordion @(Model.Classes)" data-module="govuk-accordion" @(!string.IsNullOrEmpty(Model.Id) ? $"Id = {Model.Id}" : $@"Id = {"accordion-default"}")
I am now using this assumption.

2020-02-14 14:05 UTC, asprouc commented on GovUkDesignSystemComponents/Accordion.cshtml
> +                            <span class="govuk-accordion__section-button" id="accordion-with-summary-sections-heading-1">
Done.

2020-02-14 14:05 UTC, asprouc commented on GovUkDesignSystemComponents/Accordion.cshtml
> +                        <div class="govuk-accordion__section-summary govuk-body" id="accordion-with-summary-sections-summary-1">
Done.

2020-02-14 14:06 UTC, asprouc commented on GovUkDesignSystemComponents/Accordion.cshtml
> +                    <div id="accordion-default-content-1" class="govuk-accordion__section-content" aria-labelledby="accordion-default-heading-1">
Done.

2020-02-14 14:06 UTC, asprouc commented on GovUkDesignSystemComponents/AccordionViewModel.cs
> +        public int HeadingLevel { get; set; } = 2;
OK done.

2020-02-14 14:06 UTC, asprouc commented on GovUkDesignSystemComponents/Accordion.cshtml
> +                        <p class='govuk-body'>
Corrected.

2020-02-14 14:16 UTC, asprouc commented on GovUkDesignSystemComponents/AccordionViewModel.cs
> +        public int HeadingLevel { get; set; }
Waqar has created a separate branch and pull request for this change.

2020-02-17 11:52 UTC, DanCorder approved these changes
Looks good thanks. Please don't merge yet though

2020-02-17 12:20 UTC, DanCorder commented on GovUkDesignSystemComponents/AccordionViewModel.cs
> +        public int HeadingLevel { get; set; }
I've merged Waqar's enum on to a new "new-components" branch. But his changes don't include any modifications to the Accordian so you'll need to make use of it here. We can discuss how to sort out git so this works.

2020-02-18 12:06 UTC, DanCorder approved these changes

2020-02-18 12:07 UTC, merged